// merces/src/components/inputs-and-interactive/modal-field/min-max-modal-group/min-max-modal-group.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
} from '@angular/core';

export type MinMaxModalGroupLayout = 'vertical' | 'horizontal';

@Component({
  selector: 'merces-min-max-modal-group',
  standalone: true,
  templateUrl: './min-max-modal-group.component.html',
  styleUrl: './min-max-modal-group.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class.minmax--vertical]': 'layout() === "vertical"',
    '[class.minmax--horizontal]': 'layout() === "horizontal"',
    '[class.minmax--span]': 'span()',
  },
})
export class MinMaxModalGroupComponent {
  readonly layout = input<MinMaxModalGroupLayout>('vertical');
  readonly span = input<boolean>(false);
  readonly label = input<string>('Label Text');
}

// merces-ds/react/src/components/Inputs and Interactive/Modal Field/MinMaxModalGroup/MinMaxModalGroup.tsx
import type { ReactNode } from 'react';
import './MinMaxModalGroup.module.css';

export type MinMaxModalGroupLayout = 'vertical' | 'horizontal';

export interface MinMaxModalGroupProps {
  /** Label text */
  label: string;
  /** Layout direction */
  layout?: MinMaxModalGroupLayout;
  /** Two <ModalField> children (min + max) */
  children: ReactNode;
  /** Extra className */
  className?: string;
}

export function MinMaxModalGroup({
  label,
  layout = 'vertical',
  children,
  className,
}: MinMaxModalGroupProps) {
  const classes = [
    'mds-minmax-modal-group',
    `mds-minmax-modal-group--${layout}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes}>
      <span className="mds-minmax-modal-group__label">{label}</span>
      <div className="mds-minmax-modal-group__inputs">{children}</div>
    </div>
  );
}
