// merces-ds/src/components/inputs-and-interactive/dropdown/dropdown-dependencies/dropdown-item/dropdown-item.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  input,
  output,
  computed,
  HostBinding,
  HostListener,
} from '@angular/core';
import { IconComponent } from '../../../../../assets/icon/icon.component';
import {
  DropdownItemMode,
  DropdownItemOrientation,
  DropdownItemState,
} from './dropdown-item.types';

@Component({
  selector: 'merces-dropdown-item',
  standalone: true,
  imports: [IconComponent],
  templateUrl: './dropdown-item.component.html',
  styleUrl: './dropdown-item.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'role': 'option',
    '[class.dropdown-item--single-select]': 'mode() === "single-select"',
    '[class.dropdown-item--multi-select]': 'mode() === "multi-select"',
    '[class.dropdown-item--choice]': 'mode() === "choice"',
    '[class.dropdown-item--left]': 'orientation() === "left"',
    '[class.dropdown-item--right]': 'orientation() === "right"',
    '[class.dropdown-item--checked]': 'checked()',
    '[class.dropdown-item--disabled]': 'state() === "disabled"',
    '[class.dropdown-item--highlighted]': 'highlighted()',
    '[class.dropdown-item--truncate]': 'truncateText()',
    '[attr.id]': 'itemId() || null',
    '[attr.aria-selected]': 'checked()',
    '[attr.aria-disabled]': 'isDisabled() ? "true" : null',
    '[tabindex]': 'isDisabled() ? -1 : 0',
  },
})
export class DropdownItemComponent {
  /* ── Inputs ── */
  readonly mode = input<DropdownItemMode>('single-select');
  readonly orientation = input<DropdownItemOrientation>('left');
  readonly checked = input<boolean>(false);
  readonly state = input<DropdownItemState>('default');
  readonly highlighted = input<boolean>(false);
  readonly moreInfo = input<boolean>(false);
  readonly truncateText = input<boolean>(false);
  readonly itemId = input<string | undefined>(undefined);
  readonly label = input<string>('Item');

  /* ── Outputs ── */
  readonly selected = output<void>();
  readonly infoClicked = output<void>();

  /* ── Computed ── */
  readonly isSingleSelect = computed(() => this.mode() === 'single-select');
  readonly isMultiSelect = computed(() => this.mode() === 'multi-select');
  readonly isChoice = computed(() => this.mode() === 'choice');
  readonly isLeft = computed(() => this.orientation() === 'left');
  readonly isDisabled = computed(() => this.state() === 'disabled');

  /* ── Keyboard focus tracking ── */
  private _keyboardFocused = false;
  private _focusFromMouse = false;

  @HostBinding('class.dropdown-item--keyboard-focus')
  get keyboardFocused(): boolean { return this._keyboardFocused; }

  @HostListener('mousedown') onMouseDown(): void {
    this._focusFromMouse = true;
    this._keyboardFocused = false;
  }

  @HostListener('focus') onFocus(): void {
    this._keyboardFocused = !this._focusFromMouse;
    this._focusFromMouse = false;
  }

  @HostListener('blur') onBlur(): void {
    this._keyboardFocused = false;
  }

  @HostListener('click') onClick(): void { this._selectIfEnabled(); }
  @HostListener('keydown.enter') onEnter(): void { this._selectIfEnabled(); }
  @HostListener('keydown.space', ['$event']) onSpace(e: Event): void {
    e.preventDefault();
    this._selectIfEnabled();
  }

  onInfoClick(event: Event): void {
    event.stopPropagation();
    this.infoClicked.emit();
  }

  private _selectIfEnabled(): void {
    if (!this.isDisabled()) {
      this.selected.emit();
    }
  }
}

<!-- ══════════════════════════════════════════════════
     SingleSelect · Left
     Figma: Main Content > [Icon-Check Frame, Item]
     MoreInfo: Icon-Info Frame is sibling of Main Content
     ══════════════════════════════════════════════════ -->
@if (isSingleSelect() && isLeft()) {
  <div class="main-content">
    <span class="icon-check-frame" [class.icon-check--visible]="checked()">
      <merces-icon name="tick" size="tiny" type="bold" />
    </span>
    <span
      class="paragraph-ui item-text"
      [class.item-text--truncate]="truncateText()"
    >{{ label() }}</span>
  </div>
  @if (moreInfo()) {
    <span class="icon-info-frame" (click)="onInfoClick($event)">
      <merces-icon name="information-circle" size="mini" type="regular" />
    </span>
  }
}

<!-- ══════════════════════════════════════════════════
     SingleSelect · Right
     Figma: Main Content (gap 6) > [Item], Icon-Check Frame
     MoreInfo: Icon-Info Frame is sibling of Main Content
     ══════════════════════════════════════════════════ -->
@else if (isSingleSelect() && !isLeft()) {
  <div class="main-content main-content--right-ss">
    <span
      class="paragraph-ui item-text"
      [class.item-text--truncate]="truncateText()"
    >{{ label() }}</span>
  </div>
  @if (moreInfo()) {
    <span class="icon-info-frame" (click)="onInfoClick($event)">
      <merces-icon name="information-circle" size="mini" type="regular" />
    </span>
  }
  <span class="icon-check-frame" [class.icon-check--visible]="checked()">
    <merces-icon name="tick" size="tiny" type="bold" />
  </span>
}

<!-- ══════════════════════════════════════════════════
     MultiSelect · Left
     Figma: Checkbox > Box > [Tick], Main Content > [Text, (Icon-Info)]
     MoreInfo: Icon-Info is INSIDE Main Content
     ══════════════════════════════════════════════════ -->
@else if (isMultiSelect() && isLeft()) {
  <span class="checkbox">
    <span class="checkbox-box" [class.checkbox-box--checked]="checked()" [class.checkbox-box--disabled]="isDisabled()">
      <merces-icon class="checkbox-tick" name="tick" size="tiny" type="bold" />
    </span>
  </span>
  <div class="main-content">
    <span
      class="paragraph-ui-thin item-text"
      [class.item-text--truncate]="truncateText()"
    >{{ label() }}</span>
    @if (moreInfo()) {
      <span class="icon-info-frame" (click)="onInfoClick($event)">
        <merces-icon name="information-circle" size="mini" type="regular" />
      </span>
    }
  </div>
}

<!-- ══════════════════════════════════════════════════
     Choice · Justified
     Figma: Main Content > [Item]
     No selection indicator. No More Info.
     ══════════════════════════════════════════════════ -->
@else if (isChoice()) {
  <div class="main-content">
    <span
      class="paragraph-ui item-text"
      [class.item-text--truncate]="truncateText()"
    >{{ label() }}</span>
  </div>
}

<!-- ══════════════════════════════════════════════════
     MultiSelect · Right
     Figma: Main Content > [Text, (Icon-Info)], Checkbox > Box > [Tick]
     MoreInfo: Icon-Info is INSIDE Main Content
     ══════════════════════════════════════════════════ -->
@else {
  <div class="main-content">
    <span
      class="paragraph-ui-thin item-text"
      [class.item-text--truncate]="truncateText()"
    >{{ label() }}</span>
    @if (moreInfo()) {
      <span class="icon-info-frame" (click)="onInfoClick($event)">
        <merces-icon name="information-circle" size="mini" type="regular" />
      </span>
    }
  </div>
  <span class="checkbox">
    <span class="checkbox-box" [class.checkbox-box--checked]="checked()" [class.checkbox-box--disabled]="isDisabled()">
      <merces-icon class="checkbox-tick" name="tick" size="tiny" type="bold" />
    </span>
  </span>
}

// merces-ds/react/src/components/Inputs and Interactive/Dropdown/DropdownItem/DropdownItem.tsx
import type { ReactNode } from 'react';
import { Icon } from '../../../Assets/Icon/Icon';
import { TickBold12, InformationCircleRegular16 } from '../../../Assets/Icon/icons';
import { MoreInfo } from '../../Sub-Controls/MoreInfo/MoreInfo';
import './DropdownItem.module.css';

export type DropdownItemMode = 'single' | 'multi';
export type DropdownItemOrientation = 'left' | 'right';
export type DropdownItemState = 'default' | 'hover' | 'pressed' | 'disabled';

export interface DropdownItemProps {
  /** Unique ID for aria-activedescendant (keyboard nav) */
  id?: string;
  /** Item label text */
  label: string;
  /** Selection mode */
  mode?: DropdownItemMode;
  /** Tick/checkbox icon placement */
  orientation?: DropdownItemOrientation;
  /** Whether the item is selected */
  checked?: boolean;
  /** Visual state (hover/pressed also via CSS pseudo-classes) */
  state?: DropdownItemState;
  /** Whether the item is keyboard-highlighted */
  highlighted?: boolean;
  /** Truncate label text with ellipsis */
  truncate?: boolean;
  /** Show MoreInfo icon button */
  moreInfo?: boolean;
  /** Callback when MoreInfo icon is clicked */
  onMoreInfoClick?: () => void;
  /** Callback when item is selected */
  onSelect?: () => void;
  /** Extra className */
  className?: string;
}

export function DropdownItem({
  id,
  label,
  mode = 'single',
  orientation = 'left',
  checked = false,
  state = 'default',
  highlighted = false,
  truncate = false,
  moreInfo = false,
  onMoreInfoClick,
  onSelect,
  className,
}: DropdownItemProps) {
  const classes = [
    'mds-dropdown-item',
    checked && 'mds-dropdown-item--checked',
    state === 'hover' && 'mds-dropdown-item--hover',
    state === 'pressed' && 'mds-dropdown-item--pressed',
    state === 'disabled' && 'mds-dropdown-item--disabled',
    highlighted && 'mds-dropdown-item--highlighted',
    truncate && 'mds-dropdown-item--truncate',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const isDisabled = state === 'disabled';

  /* Tick icon for SingleSelect */
  const tickIcon = (
    <span className="mds-dropdown-item__tick">
      <Icon size="tiny">{TickBold12}</Icon>
    </span>
  );

  /* Checkbox for MultiSelect */
  const checkbox = (
    <span className="mds-dropdown-item__checkbox">
      <span className="mds-dropdown-item__checkbox-box">
        <span className="mds-dropdown-item__checkbox-icon">
          <Icon size="tiny">{TickBold12}</Icon>
        </span>
      </span>
    </span>
  );

  /* Main content — label with optional tick (SingleSelect) */
  const labelEl = (
    <span className="mds-dropdown-item__label">{label}</span>
  );

  /* Build content based on mode and orientation */
  let content: ReactNode;

  if (mode === 'single') {
    if (orientation === 'left') {
      content = (
        <span className="mds-dropdown-item__content">
          {tickIcon}
          {labelEl}
        </span>
      );
    } else {
      /* Right: label first, then tick icon outside content */
      content = (
        <>
          <span className="mds-dropdown-item__content">
            {labelEl}
          </span>
          {tickIcon}
        </>
      );
    }
  } else {
    /* MultiSelect */
    if (orientation === 'left') {
      content = (
        <>
          {checkbox}
          <span className="mds-dropdown-item__content">
            {labelEl}
          </span>
        </>
      );
    } else {
      content = (
        <>
          <span className="mds-dropdown-item__content">
            {labelEl}
          </span>
          {checkbox}
        </>
      );
    }
  }

  return (
    <div
      id={id}
      className={classes}
      role="option"
      aria-selected={checked}
      aria-disabled={isDisabled || undefined}
      onClick={!isDisabled ? onSelect : undefined}
    >
      {content}
      {moreInfo && (
        <span className="mds-dropdown-item__more-info">
          <MoreInfo
            icon={
              <Icon size="mini">{InformationCircleRegular16}</Icon>
            }
            text=""
            onClick={(e) => {
              e.stopPropagation();
              onMoreInfoClick?.();
            }}
          />
        </span>
      )}
    </div>
  );
}
